import { GoogleGenAI } from "@google/genai";
import { NextResponse } from "next/server";

export async function POST(req: Request) {
  try {
    const { items, dishCount, peopleCount, isAllItems } = await req.json();

    if (!items || items.length === 0) {
      return NextResponse.json({ error: "No items selected." }, { status: 400 });
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      console.error("GEMINI_API_KEY is missing from environment variables.");
      return NextResponse.json({ error: "Gemini API key is not configured." }, { status: 500 });
    }

    // Initialize the client
    const client = new GoogleGenAI({ apiKey });

    const prompt = `
      你是一位大廚。我冰箱裡有以下食材：
      ${items.map((i: any) => `- ${i.name} ${i.amount ? `(${i.amount})` : ""} (過期日：${i.expireDate})`).join("\n")}

      ${isAllItems ? "請優先考慮快過期的食材，並盡可能靈活地組合這些食材。" : "請專注於使用我選中的這些食材。"}
      
      請根據這些食材提供 ${dishCount} 道供 ${peopleCount} 人食用的菜餚。
      每道菜請提供：
      1. 菜名。
      2. 逐步的烹飪指令。
      3. 保持簡單實用。

      請嚴格以以下 JSON 格式回答（不要使用 markdown 代碼塊）：
      {
        "dishes": [
          {
            "name": "菜名",
            "steps": ["步驟 1", "步驟 2", "..."]
          }
        ]
      }
    `;

    console.log("正在為以下食材生成食譜：", items.map((i: any) => i.name).join(", "));
    
    const result = await client.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
      config: {
        responseMimeType: "application/json"
      }
    });

    // Detailed logging of the result to debug structure
    // console.log("Gemini Result:", JSON.stringify(result, null, 2));

    const text = result.candidates?.[0]?.content?.parts?.[0]?.text;
    
    if (!text) {
      console.error("Gemini response did not contain text parts:", JSON.stringify(result, null, 2));
      throw new Error("No content generated by Gemini.");
    }

    return NextResponse.json(JSON.parse(text));
  } catch (error: any) {
    console.error("Gemini API error details:", error);
    return NextResponse.json({ 
      error: error.message || "Failed to generate recipes.",
      details: error.stack
    }, { status: 500 });
  }
}
